openapi: 3.0.0
info:
  title: Tasks API
  description: API for managing tasks and projects
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created

  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task found
        '404':
          description: Task not found
    put:
      summary: Update task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
        '404':
          description: Task not found
    delete:
      summary: Delete task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task deleted
        '404':
          description: Task not found

  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: List of projects
    post:
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Project created

  /projects/{id}:
    get:
      summary: Get project by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project found
        '404':
          description: Project not found
    put:
      summary: Update project by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Project updated
        '404':
          description: Project not found
    delete:
      summary: Delete project by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project deleted
        '404':
          description: Project not found

components:
  schemas:
    Task:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        completed:
          type: boolean
        priority:
          type: string
          enum: [low, medium, high]
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time

    Project:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date
