paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
        '401':
          description: Unauthorized
        '500':
          description: Server error
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task found
        '404':
          description: Task not found
        '401':
          description: Unauthorized
    put:
      summary: Update task by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
    delete:
      summary: Delete task by ID
      responses:
        '204':
          description: Task deleted
        '401':
          description: Unauthorized
        '404':
          description: Task not found

  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: List of projects
    post:
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Project created
        '400':
          description: Invalid input

  /projects/{id}:
    get:
      summary: Get project by ID
      responses:
        '200':
          description: Project found
        '404':
          description: Project not found
    put:
      summary: Update project by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Project updated
        '400':
          description: Invalid input
    delete:
      summary: Delete project by ID
      responses:
        '204':
          description: Project deleted
        '404':
          description: Project not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
